### ISSUE TITLE
Need survey embed code

### ISSUE THREAD

**Issue by bradmac** [anhnt/kfeedback#10]
From a survey management page (http://admin.sonnh.olhub.com/kfeedback/#\/surveys/detail/?id=qqwqw) i should be given a complete code snippet suitable for inserting into email

I suggest that when a survey is created it is initially defaulted to having 3 options - happy, neutral, sad

The default code snippet emoticon images and links, and the default appearance is simply the icons with no text. Eg would look something like this:
https://firnecast.files.wordpress.com/2014/09/faces.jpg

Currently there is no way to associate options configured for a survey with emoticons. What i suggest is that the options are used as filenames. eg:

```
<a href="http://site1.olhub.com/send-feedback/?survey=brads-customer-feedback&option=0-happy&@{login}">
    happy
</a>

<a href="http://site1.olhub.com/send-feedback/?survey=brads-customer-feedback&option=1-neutral&@{login}">
    neutral
</a>

<a href="http://site1.olhub.com/send-feedback/?survey=brads-customer-feedback&option=2-sad&@{login}">
    sad
</a>
```

**Comment by juzser** [comment]
I updated and modified layout a little. 
Please check

**Comment by bradmac** [comment]
I cant find the embed code. I need to be able to copy and paste a single piece of html code into my email. I'm looking here, cant see it:
http://admin.sonnh.olhub.com/kfeedback/#\/surveys/survey-son
