### ISSUE TITLE
No thank you page

### ISSUE THREAD

**Issue by Uafinder** [anhnt/kfeedback#12]
I've create a survey, copied a content to email, sent email, and tried to click on any emotion... it gives me a login page instead of thank you page... why? looks like there are a automatic redirection to dashboard
![image](https://cloud.githubusercontent.com/assets/1945230/14616380/ebdd7620-05b2-11e6-9e06-2d1167951063.png)

**Comment by anhnt** [comment]
I can see you've created this survey without any redirection page http://admin.minda.olhub.com/kfeedback/#!/surveys/detail/?id=simple-test-from-vlad

Those fields should be validated...
